### ISSUE TITLE
doesnt work on docker for Mac

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-preload#21] opened 2017-01-04 17:39 UTC
Get the following error:
```shaun-mbp-2:resin-preload-image-script hobochild$ docker run -it -e API_TOKEN=$API_TOKEN -e APP_ID=$APP_ID -v $PATH_TO_IMAGE:/img/resin.img --privileged resin/resin-preload
Loading the following image:  chromium/e91b20b6abfeb6d353e6e659c9d2af3178d1fc58
container size:  191 MB
301+0 records in
301+0 records out
mount: unknown filesystem type 'btrfs'
Waiting for Docker to stop...
```

**Comment by KemperVreden** [comment] 2017-01-16 12:32
Yepp! Same for me here. Tried it on Ubuntu but there it just says:

`Waiting for Docker stop...`

**Comment by jhermsmeier** [comment] 2017-01-16 12:51
@shaunmulligan @KemperVreden with which Resin OS versions does that happen?

**Comment by shaunmulligan** [comment] 2017-01-16 12:54
@jhermsmeier I tried with resinOS 1.24.1 on rpi3 from production. It doesn't seem to work on macOS because the thin hypervisor kernel they have in docker for Mac doesnt have the correct settings for btrfs.

but Ubuntu 16.10 worked correctly for me after this PR: https://github.com/resin-io/resin-preload-image-script/pull/20

**Comment by KemperVreden** [comment] 2017-01-16 12:54
1.24.0 - Tested yesterday. On Raspberry Pi running stock-Raspbian it ran but got an error which said something about the "GO"-language when compiling something ... I can reproduce the output but since I am more interested running this script on OS X (macOS - I know) ...

**Comment by jhermsmeier** [comment] 2017-01-16 14:46
Apparently they removed BTRFS support from Docker for Mac: docker/for-mac#388
The only workaround for this at the moment that comes to mind is using the "old" docker toolbox setup with VirtualBox.

@KemperVreden What docker version are you running on Ubuntu?

**Comment by KemperVreden** [comment] 2017-01-17 19:36
@jhermsmeier I am using 16.04 LTS

**Comment by jhermsmeier** [comment] 2017-01-17 19:45
@KemperVreden Sadly it doesn't look like BTRFS support will get back into Docker for Mac very soon, but I just merged the new version with enhanced log output and some other things – could you try that on Ubuntu and post the output, if it fails? That would be very helpful.

Keep in mind you'll have to run `docker build -t resin/resin-preload .` beforehand, as it won't use the updated version otherwise.

**Comment by KemperVreden** [comment] 2017-01-17 20:05
Ok so running `docker build -t resin/resin-preload .` leads to: https://gist.github.com/KemperVreden/314f246901b61fcca16f943a947be932

Running the script returns: `Waiting for Docker to stop...`

**Comment by jhermsmeier** [comment] 2017-01-17 20:35
> Ok so running docker build -t resin/resin-preload . leads to: https://gist.github.com/KemperVreden/314f246901b61fcca16f943a947be932

This looks like there's something wrong with the network there:
```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.4/main: temporary error (try again later)
```
I checked and it seems to be up & available:
```
$ curl -I http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
```
```
HTTP/1.1 200 OK
Content-Type: application/x-gzip
Accept-Ranges: bytes
ETag: "921748257"
Last-Modified: Fri, 13 Jan 2017 09:59:26 GMT
Content-Length: 675268
...
```
Does restarting docker completely & retrying help?

> Running the script returns: `Waiting for Docker to stop...`

Yeah, that's to be expected if the build step fails.

**Comment by KemperVreden** [comment] 2017-01-19 11:19
@jhermsmeier Sure! I hade some bad network settings in my Ubuntu-VM. Fixed it and I successfully tried it again today. I cannot test the image but seems like everything just worked as expected!?

https://gist.github.com/KemperVreden/529ca26488b16e03e060a9da91b7bdd8

**Comment by jhermsmeier** [comment] 2017-01-19 11:34
@KemperVreden Nice, I'm glad it eventually worked! The output looks good, so if you used the current up-to-date master (there was a fix that went into it yesterday), the image should be fine as well.

**Comment by jhermsmeier** [comment] 2017-07-05 16:42
I'm closing this, as it appears resolved, and the documentation states the known issues around having to use the old Docker Toobox for btrfs support.

**Closed by jhermsmeier** 2017-07-05 16:42 UTC
Labels: upstream
